[[LIBMINC]]
arch = "x86_64"
git-tree-sha1 = "c57cd611627f658d87c4aa876fda826253875cd2"
libc = "glibc"
os = "linux"

    [[LIBMINC.download]]
    sha256 = "5c335d7b6057e28d5962cf1dadef2bf848954d3a8ee5625f5bec7e319b48ec2f"
    url = "https://github.com/vfonov/LIBMINC_jll.jl/releases/download/LIBMINC-v2.4.10+0/LIBMINC.v2.4.10.x86_64-linux-gnu.tar.gz"
