[[LIBMINC]]
arch = "x86_64"
git-tree-sha1 = "eff49cb737a937a32b81547acdfe8f99f9600a38"
libc = "glibc"
os = "linux"

    [[LIBMINC.download]]
    sha256 = "059a7787d4895610285469edbfe55587aeb281adc3eb533f189bcc963cb3d7f8"
    url = "https://github.com/vfonov/LIBMINC_jll.jl/releases/download/LIBMINC-v2.4.6+0/LIBMINC.v2.4.6.x86_64-linux-gnu.tar.gz"
