[[LIBMINC]]
arch = "x86_64"
git-tree-sha1 = "e1a5d0ec3a23205c7ca6496ee2b3bd08531e242b"
libc = "glibc"
os = "linux"

    [[LIBMINC.download]]
    sha256 = "3e8d4182bcee7673084fd15a132a2db3bd21df958b982af1a1ba80fb4d0e8c2b"
    url = "https://github.com/vfonov/LIBMINC_jll.jl/releases/download/LIBMINC-v2.4.10+0/LIBMINC.v2.4.10.x86_64-linux-gnu.tar.gz"
