[[libminc]]
arch = "x86_64"
git-tree-sha1 = "959f404568fbc4e19ac99b56224bf31cdac21a62"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[libminc.download]]
    sha256 = "9bbe0a41b9b38f11624b7fd965b948f3484f796a0d1ea96dcecdbaae7a80d1cd"
    url = "https://github.com/vfonov/libminc_jll.jl/releases/download/libminc-v2.5.0+0/libminc.v2.5.0.x86_64-linux-gnu-libgfortran5-mpi+mpitrampoline.tar.gz"
[[libminc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfdc7c0efcba3cc0b1cd92cfe6f8e3c0d87fd974"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpich"
os = "linux"

    [[libminc.download]]
    sha256 = "11b55d956e177cfb060bf6e9aa8baf6967a0f548692bbc1b3311c8173db29adb"
    url = "https://github.com/vfonov/libminc_jll.jl/releases/download/libminc-v2.5.0+0/libminc.v2.5.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpich.tar.gz"
[[libminc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "959f404568fbc4e19ac99b56224bf31cdac21a62"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "mpitrampoline"
os = "linux"

    [[libminc.download]]
    sha256 = "9bbe0a41b9b38f11624b7fd965b948f3484f796a0d1ea96dcecdbaae7a80d1cd"
    url = "https://github.com/vfonov/libminc_jll.jl/releases/download/libminc-v2.5.0+0/libminc.v2.5.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+mpitrampoline.tar.gz"
[[libminc]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "6de0c7bd270d56500fee4958b8475ebd999dd1c6"
libc = "glibc"
libgfortran_version = "5.0.0"
mpi = "openmpi"
os = "linux"

    [[libminc.download]]
    sha256 = "47d9b73b0215811fd526e576f1e71720cb20430d09589812228457699dc95451"
    url = "https://github.com/vfonov/libminc_jll.jl/releases/download/libminc-v2.5.0+0/libminc.v2.5.0.x86_64-linux-gnu-libgfortran5-cxx11-mpi+openmpi.tar.gz"
[[libminc]]
arch = "x86_64"
git-tree-sha1 = "66147e7f97bcbc234060e82174dabe10d53b5910"
libc = "glibc"
os = "linux"

    [[libminc.download]]
    sha256 = "0a497c792a3751fc63d8cad4c5ee721f339c7dfc4cda7dcbd18ea62ec9aa2400"
    url = "https://github.com/vfonov/libminc_jll.jl/releases/download/libminc-v2.5.0+0/libminc.v2.5.0.x86_64-linux-gnu.tar.gz"
[[libminc]]
arch = "x86_64"
git-tree-sha1 = "e8041aced0e3ce88fde476bda3afe6dd7b1701ea"
libc = "musl"
os = "linux"

    [[libminc.download]]
    sha256 = "ad7604d0d1aeadbbfd0845a8143c67948d22df0874cc18dca049bc012c089736"
    url = "https://github.com/vfonov/libminc_jll.jl/releases/download/libminc-v2.5.0+0/libminc.v2.5.0.x86_64-linux-musl.tar.gz"
