[[LIBMINC]]
arch = "x86_64"
git-tree-sha1 = "34fb054bd3e43e4665f22091a746b72208c9e5e9"
libc = "glibc"
os = "linux"

    [[LIBMINC.download]]
    sha256 = "6f74a5ba12fc1dbba8cfbba7c4cbe414833c272fe873d36ad3a9ead213e67662"
    url = "https://github.com/vfonov/LIBMINC_jll.jl/releases/download/LIBMINC-v2.4.11+0/LIBMINC.v2.4.11.x86_64-linux-gnu.tar.gz"
