[[LIBMINC]]
arch = "x86_64"
git-tree-sha1 = "dbd57559afb23e9fde43ab6f4608771ebf2eba6f"
libc = "glibc"
os = "linux"

    [[LIBMINC.download]]
    sha256 = "01b8e7ce8fa59302f78aafd631bb1c72de6c2ed8eeea4ab4cd25f74ad1925174"
    url = "https://github.com/vfonov/LIBMINC_jll.jl/releases/download/LIBMINC-v2.4.5+0/LIBMINC.v2.4.5.x86_64-linux-gnu.tar.gz"
